import test from 'node:test';
import assert from 'node:assert/strict';
import { draftImageTool } from '../../packages/template-editor-shell/src/ai-image-tool.js';

const png = Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4n+DwHwAGoAKfr+/eKAAAAABJRU5ErkJggg=='), value => value.charCodeAt(0));
const original = { 'index.tpl': '@layout\n<h1>Page</h1>\n@endlayout' };
const input = path => ({ path, prompt: 'Generate the requested surgeon portrait.', referenceIds: [] });

test('generated images retain the requested safe project path outside the images directory', async () => {
  let files = { ...original }, calls = 0;
  const committed = [], events = [];
  const tool = draftImageTool({ generateImage: async () => { calls++; return png; }, getFiles: () => files,
    commit(next, path) { files = next; committed.push(path); }, onProgress: event => events.push(event) });
  const paths = ['img/qa-generated-surgeon.png', 'assets/photos/surgeon.png', 'surgeon.png', 'img/lekarz-żółć.PNG'];
  for (const path of paths) {
    assert.deepEqual(await tool.execute(input(path)), { ok: true, path });
    assert.strictEqual(files[path], png, 'commit the PNG bytes at the exact requested path');
  }
  assert.equal(calls, paths.length, 'each requested asset makes exactly one image request');
  assert.deepEqual(committed, paths);
  assert.deepEqual(events.filter(event => event.type === 'image-start').map(event => event.path), paths);
  assert.equal(files['index.tpl'], original['index.tpl']);
  assert.deepEqual(Object.keys(original), ['index.tpl'], 'draft generation leaves original files untouched');
  assert.equal(Object.keys(files).some(path => path.startsWith('images/')), false, 'the tool does not invent a replacement directory');
});

test('unsafe paths and non-PNG extensions are rejected before any image request or budget consumption', async () => {
  let files = { ...original }, calls = 0;
  const events = [];
  const tool = draftImageTool({ generateImage: async () => { calls++; return png; }, getFiles: () => files,
    commit(next) { files = next; }, onProgress: event => events.push(event) });
  const rejectedPaths = ['', '../surgeon.png', 'img/../surgeon.png', '/tmp/surgeon.png', 'C:\\surgeon.png',
    'img//surgeon.png', 'img/.hidden.png', '__proto__/surgeon.png', 'img/surgeon.jpg', 'img/surgeon.png?download=1',
    'img/%2e%2e/surgeon.png', 'img/surgeon portrait.png'];
  for (const path of rejectedPaths) {
    const result = await tool.execute(input(path));
    assert.equal(result.ok, false, path);
    assert.ok(result.error, path);
  }
  assert.equal(calls, 0, 'invalid paths never reach the paid generator');
  assert.deepEqual(files, original);
  assert.equal(events.some(event => event.type === 'image-start'), false);
  assert.equal(events.filter(event => event.type === 'image-error').length, rejectedPaths.length);
  assert.deepEqual(await tool.execute(input('img/valid.png')), { ok: true, path: 'img/valid.png' });
  assert.equal(calls, 1, 'rejected paths do not consume the four-request limit');
});

test('existing and concurrent duplicate paths cannot overwrite assets or issue repeat image requests', async () => {
  const existing = Uint8Array.of(1, 2, 3);
  let files = { ...original, 'img/existing.png': existing }, calls = 0, commits = 0, complete;
  const waiting = new Promise(resolve => { complete = resolve; });
  const tool = draftImageTool({ generateImage: async () => { calls++; return waiting; }, getFiles: () => files,
    commit(next) { files = next; commits++; } });
  assert.equal((await tool.execute(input('img/existing.png'))).ok, false);
  assert.equal(calls, 0);
  assert.strictEqual(files['img/existing.png'], existing);

  const first = tool.execute(input('assets/photos/pending.png'));
  assert.equal(calls, 1);
  for (let repeat = 0; repeat < 2; repeat++) {
    assert.equal((await tool.execute(input('assets/photos/pending.png'))).ok, false);
    assert.equal(calls, 1, 'a rejected duplicate must not release another call\'s pending reservation');
  }
  complete(png);
  assert.deepEqual(await first, { ok: true, path: 'assets/photos/pending.png' });
  assert.equal(commits, 1);
  assert.strictEqual(files['assets/photos/pending.png'], png);
  assert.equal((await tool.execute(input('assets/photos/pending.png'))).ok, false);
  assert.equal(calls, 1, 'a completed path is reusable by the page, never regenerated by this tool');
});

test('safe paths in different directories still share the four-image request limit', async () => {
  let files = { ...original }, calls = 0;
  const tool = draftImageTool({ generateImage: async () => { calls++; return png; }, getFiles: () => files,
    commit(next) { files = next; } });
  for (const path of ['img/one.png', 'assets/photos/two.png', 'three.png', 'nested/four.png']) {
    assert.equal((await tool.execute(input(path))).ok, true);
  }
  const rejected = await tool.execute(input('img/five.png'));
  assert.equal(rejected.ok, false);
  assert.match(rejected.error, /limit of 4/);
  assert.equal(calls, 4);
  assert.equal(files['img/five.png'], undefined);
});
