import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname, resolve } from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = resolve(process.argv[2] || 'editor/dist');
const types = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css', '.svg':'image/svg+xml', '.png':'image/png', '.json':'application/json', '.webmanifest':'application/manifest+json', '.woff2':'font/woff2' };
const server = createServer(async (req,res) => { try { const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname); const file=resolve(join(root,path==='/'?'index.html':path)); if(!file.startsWith(root+'/'))throw Error('path'); const value=await readFile(file); res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'}); res.end(value); } catch {res.writeHead(404);res.end('Not found');} });
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;
try {
 browser=await chromium.launch({headless:true,...(process.platform==='darwin'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
 const page=await browser.newPage({viewport:{width:1600,height:1100}}), errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.getByRole('button', { name: 'New project', exact: true }).click();
 await page.getByRole('textbox', { name: 'Project name', exact: true }).fill('Browser test');
 await page.getByRole('button', { name: 'Create landing', exact: true }).click();
 await page.locator('.browser-frame iframe').waitFor();
 assert.equal(await page.getByRole('tab',{name:'AI assistant',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Manage project folders',exact:true}).count(),0);
 await page.addInitScript(() => Object.defineProperty(navigator, 'standalone', { configurable: true, value: true }));
 await page.reload();
 await page.getByRole('button',{name:'Collapse editor',exact:true}).click();
 await page.getByRole('tab',{name:'AI assistant',exact:true}).click();
 await page.getByRole('button',{name:'AI connection settings',exact:true}).click();
 await page.locator('.ai-settings input[type=password]').waitFor();
 assert.equal(await page.getByRole('tab',{name:'AI assistant',exact:true}).getAttribute('aria-selected'),'true');
 await page.getByRole('button',{name:'Back to assistant',exact:true}).click();
 await page.getByRole('tab',{name:'Content',exact:true}).click();
 await page.evaluate(()=>{document.body.style.overflow='auto';document.querySelector('.workspace').style.transform='translateX(0)';});
 await page.locator('.hosted-more > summary').click();
 const expand=page.getByRole('button',{name:'Expand editor',exact:true}); await expand.click();
 await page.locator('.editor-shell.is-expanded').waitFor();
 const box=await page.locator('.editor-shell').boundingBox(); assert.equal(box.x,0);assert.equal(box.y,0);assert.equal(box.width,1600);assert.equal(box.height,1100);
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');
 await page.getByRole('button',{name:'Create file or folder',exact:true}).click();
 await page.keyboard.press('Escape');assert.equal(await page.locator('.editor-shell.is-expanded').count(),1);assert.equal(await page.getByRole('menu',{name:'Create file or folder'}).count(),0);
 await page.getByRole('button',{name:'Rename',exact:true}).click();await page.getByRole('dialog',{name:'Rename file',exact:true}).waitFor();
 assert.equal(await page.locator('.editor-shell').getAttribute('aria-modal'),null);
 await page.keyboard.press('Escape'); assert.equal(await page.locator('.editor-shell.is-expanded').count(),1);
 await page.getByRole('button',{name:'Mobile preview',exact:true}).click();assert.ok(Math.abs((await page.locator('.browser-frame').boundingBox()).width-375)<1);
 await page.locator('.editor-shell').screenshot({path:'/tmp/studio-shell-expanded.png'});
 await page.keyboard.press('Escape'); assert.equal(await page.locator('.editor-shell.is-expanded').count(),0);assert.equal(await page.evaluate(()=>document.body.style.overflow),'auto');
 await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='More actions');
 await page.getByRole('button',{name:'Export project',exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download',exact:true}).click();assert.match((await download).suggestedFilename(),/source\.zip$/);
 assert.deepEqual(errors,[]);
 console.log('PASS: Studio common shell, browser-tab capability limits, installed-PWA AI settings, transformed-ancestor viewport overlay, menu and modal Escape, focus restoration, 375px mobile preview, source ZIP export.');
} finally {await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
