import { useEffect, useRef } from 'react';
import { FolderOpen, FolderPlus, LoaderCircle, RefreshCw, ShieldCheck, Trash2, X } from 'lucide-react';
import { projectLocation } from './ProjectSwitcher.jsx';
export function TourDialog({ onClose, installedMode = false }) {
  const nativeDialog = useRef(null);
  useEffect(() => { nativeDialog.current.showModal(); }, []);
  return <dialog ref={nativeDialog} className="modal" aria-labelledby="tour-title" onCancel={onClose}><div className="modal-box tour-modal"><div className="dialog-heading"><div><span className="section-kicker">QUICK START</span><h2 id="tour-title">From template to finished pages</h2></div><button type="button" className="btn btn-ghost btn-sm btn-square" aria-label="Close quick start" onClick={onClose}><X size={18} /></button></div><ol className="tour-steps"><li><span>1</span><div><strong>Add your project</strong><p>{installedMode ? 'Create a landing or reusable template from a starter, from scratch, or with AI. You can also import a ZIP or connect a folder.' : 'Create a landing or reusable template from a starter or a blank page, or import a source ZIP. Install Studio for AI and project folders.'}</p></div></li><li><span>2</span><div><strong>Build the template</strong><p>Edit TPL, CSS, and other source files. Changes in Content update the preview live.</p></div></li><li><span>3</span><div><strong>Choose images</strong><p>Image parameters can use existing project assets or files dropped from your computer.</p></div></li><li><span>4</span><div><strong>Take it with you</strong><p>Projects autosave on this device. Download generated pages and export source ZIPs for portable backups.</p></div></li></ol><div className="tour-note"><ShieldCheck size={16} /><span>The core editor is local. AI and project folder access are available only in the installed Studio app.</span></div><div className="modal-action"><a className="btn btn-ghost" href="https://trafficops-io.github.io/tops-templates/" target="_blank" rel="noreferrer">Read full docs ↗</a><button type="button" className="btn btn-primary" onClick={onClose}>Start creating</button></div></div><button type="button" className="modal-backdrop" aria-label="Close quick start" onClick={onClose} /></dialog>;
}

export function ProjectsDialog({ projects, currentId, supported, busy, onAdd, onOpen, onForget, onReload, onLocation, onClose }) {
  const nativeDialog = useRef(null);
  useEffect(() => { nativeDialog.current.showModal(); }, []);
  return <dialog ref={nativeDialog} className="modal" aria-labelledby="projects-title" onCancel={onClose}><div className="modal-box projects-modal"><div className="dialog-heading"><div><span className="section-kicker">LOCAL WORKSPACES</span><h2 id="projects-title">Project folders</h2></div><button type="button" className="btn btn-ghost btn-sm btn-square" aria-label="Close projects" onClick={onClose}><X size={18} /></button></div>
    <p className="muted projects-intro">Each project is one folder on your computer. Edits save automatically. Browsers reveal the folder name only; enter an optional full path label to distinguish folders. This label does not change the connected folder.</p>
    {!supported && <div className="project-support-note"><strong>Folder editing is unavailable in this browser.</strong><span>Use Chrome or Edge for read/write folders. ZIP import and export continue to work here.</span></div>}
    <div className="project-list">{projects.length ? projects.map(project => <div className={`project-list-row ${project.id === currentId ? 'current' : ''}`} key={project.id}><button type="button" className="project-open" disabled={busy || !supported} onClick={() => onOpen(project)}><FolderOpen size={18} /><span><strong>{project.name}</strong><small>{projectLocation(project)}</small></span></button><label className="project-path-field"><span className="field-help">Folder path label</span><input aria-label={`Folder path for ${project.name}`} className="input input-sm" defaultValue={project.displayPath || ''} placeholder={`${project.name}/`} onBlur={event => onLocation(project, event.target.value)} /></label><div className="project-row-actions">{project.id === currentId && <button type="button" className="btn btn-ghost btn-xs btn-square" disabled={busy} title="Reload from disk" aria-label={`Reload ${project.name} from disk`} onClick={() => onReload(project)}><RefreshCw size={14} /></button>}<button type="button" className="btn btn-ghost btn-xs btn-square" disabled={busy || project.id === currentId} title="Forget folder" aria-label={`Forget ${project.name}`} onClick={() => onForget(project)}><Trash2 size={14} /></button></div></div>) : <div className="project-list-empty"><FolderOpen size={24} /><span>No project folders yet.</span></div>}</div>
    <div className="modal-action"><button type="button" className="btn btn-ghost" onClick={onClose}>Close</button><button type="button" className="btn btn-primary" disabled={!supported || busy} onClick={onAdd}>{busy ? <LoaderCircle size={16} className="spin" /> : <FolderPlus size={16} />} Add project folder</button></div>
  </div><button type="button" className="modal-backdrop" aria-label="Close projects" onClick={onClose} /></dialog>;
}

