import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Copy, FileCode2, FolderOpen, LayoutTemplate, Plus, Search, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { generateProject } from '@trafficops/template-runtime';
import { buildPreview } from '@trafficops/template-editor-shell/preview';
import { Skeleton } from '@trafficops/studio-ui/primitives';
import { studioStarters } from './studio-catalog.js';
import HomeProjectChat, { BRIEF_REQUIRED, BriefComposer, briefAttachments } from './HomeProjectChat.jsx';

function Thumbnail({ project }) {
  const [visible, setVisible] = useState(false), root = useRef(null);
  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } }, { rootMargin: '200px' });
    observer.observe(root.current); return () => observer.disconnect();
  }, []);
  const preview = useMemo(() => {
    if (!visible || !project.files) return null;
    try { const files = generateProject(project.files, project.settings || {}); return buildPreview(files, Object.keys(files).find(path => path.endsWith('.html'))); } catch { return null; }
  }, [visible, project.files, project.settings]);
  useEffect(() => () => preview?.dispose(), [preview]);
  return <div ref={root} className="library-thumbnail" aria-hidden="true">{preview ? <iframe title={`${project.name} thumbnail`} srcDoc={preview.html} sandbox="" tabIndex={-1} /> : project.files ? <div className="library-thumbnail-skeleton"><Skeleton shape="card" height="100%" /></div> : <div className="library-thumbnail-placeholder"><FolderOpen size={28} /></div>}<span>{project.builtin ? 'STARTER' : project.kind === 'template' ? 'TEMPLATE' : 'LANDING'}</span></div>;
}

export default function StudioLibrary({ projects, busy, aiEnabled = false, aiSettings, activity = [], storageMode = 'folder', onCreate, onCreateWithAi, onOpen, onDuplicate, onDelete, onImport, onFolder, onReconnect, onRemove }) {
  const [filter, setFilter] = useState('all'), [search, setSearch] = useState('');
  const shown = projects.filter(item => (filter === 'all' || item.kind === filter) && item.name.toLowerCase().includes(search.toLowerCase()));
  return <section className={`library ${aiEnabled ? 'library-with-chat' : ''}`} aria-labelledby="library-title">
    {aiEnabled ? <><HomeProjectChat busy={busy} aiSettings={aiSettings} onCreate={onCreateWithAi} /><div className="library-heading"><div><h2>Your projects</h2><p>Pick up where you left off, or start with a canvas.</p></div><div className="library-manual-actions"><button className="btn btn-ghost btn-sm" disabled={busy} onClick={() => onCreate({ mode: 'template' })}><LayoutTemplate size={15} />From a template</button><button className="btn btn-outline btn-sm" disabled={busy} onClick={() => onCreate({ mode: 'blank' })}><Plus size={15} />New project</button></div></div></> : <><div className="library-heading"><div><span className="section-kicker">YOUR WORKSPACE</span><h2 id="library-title">Ideas become pages.</h2><p>Build a landing. Craft a reusable template. Pick up where you left off.</p></div><button className="btn btn-primary" disabled={busy} onClick={() => onCreate()}><Plus size={17} />New project</button></div><div className="creation-shortcuts manual-only">{[['template', LayoutTemplate, 'From a template', 'Start with a design and make it yours.'], ['blank', FileCode2, 'Start from scratch', 'A clean canvas for your next idea.']].map(([mode, Icon, title, text]) => <button key={mode} disabled={busy} onClick={() => onCreate({ mode })}><Icon size={23} /><strong>{title}</strong><span>{text}</span><ArrowUpRight size={16} /></button>)}</div></>}
    <div className="library-tools"><div className="library-filters" role="group" aria-label="Project filter">{[['all', 'All projects'], ['landing', 'Landings'], ['template', 'Templates']].map(([key, label]) => <button key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label} <span>{projects.filter(item => key === 'all' || item.kind === key).length}</span></button>)}</div><label className="library-search"><Search size={16} /><input aria-label="Search projects" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search projects" /></label>{onImport && <button className="btn btn-ghost btn-sm" disabled={busy} onClick={onImport}><Upload size={15} />Import ZIP</button>}{onFolder && <button className="btn btn-ghost btn-sm" disabled={busy} onClick={onFolder}><FolderOpen size={15} />Open folder</button>}</div>
    {shown.length ? <div className="library-grid">{shown.map(project => <article className="library-card" key={project.id}><button className="library-preview-button" disabled={busy} aria-label={`Open ${project.name}`} onClick={() => onOpen(project)}><Thumbnail project={project} /></button><div className="library-card-body"><h3>{project.name}</h3><p>{project.kind === 'template' ? 'Reusable template' : 'Landing page'} · {new Date(project.updatedAt).toLocaleDateString()}</p>{project.unavailable && <div className="library-unavailable" role="status"><strong>Folder unavailable</strong><span>{project.unavailable}</span><div className="library-card-actions">{onReconnect && project.source === 'folder' && <button className="btn btn-outline btn-sm" disabled={busy} aria-label={`Reconnect ${project.name}`} onClick={() => onReconnect(project)}><FolderOpen size={14} />Reconnect</button>}{onRemove && project.source === 'folder' && <button className="btn btn-ghost btn-sm" disabled={busy} aria-label={`Remove ${project.name} from list`} onClick={() => onRemove(project)}>Remove from list</button>}</div></div>}{activity.some(run => run.projectId === project.id) && <p className="library-ai-status" role="status">{activity.filter(run => run.projectId === project.id).length} AI {activity.filter(run => run.projectId === project.id).length === 1 ? 'conversation working' : 'conversations working'}</p>}<div className="library-card-actions"><button className="btn btn-primary btn-sm" disabled={busy} onClick={() => onOpen(project)}>Open editor <ArrowUpRight size={14} /></button>{project.kind === 'template' && <button className="btn btn-outline btn-sm" disabled={busy} onClick={() => onCreate({ mode: 'template', source: project })}>Use template</button>}{onDuplicate && <button className="btn btn-ghost btn-sm btn-square" aria-label={`Duplicate ${project.name}`} disabled={busy} onClick={() => onDuplicate(project)}><Copy size={14} /></button>}{onDelete && <button className="btn btn-ghost btn-sm btn-square" aria-label={`Delete ${project.name}`} disabled={busy} onClick={() => onDelete(project)}><Trash2 size={14} /></button>}</div></div></article>)}</div> : <div className="library-empty"><LayoutTemplate size={28} /><h3>{search ? 'No matching projects' : filter === 'template' ? 'Your next reusable idea starts here' : 'Make your first page'}</h3><p>{search ? 'Try a different name or filter.' : aiEnabled ? 'Create from a starter, a blank page or a conversation with AI.' : 'Create from a starter or a blank page.'}</p></div>}
    <div className="library-section-heading"><div><span className="section-kicker">A HEAD START</span><h2>Made to be yours</h2></div><p>Included starters · available offline</p></div><div className="library-grid starter-grid">{studioStarters.map(project => <article className="library-card" key={project.id}><button className="library-preview-button" aria-label={`Use ${project.name}`} disabled={busy} onClick={() => onCreate({ mode: 'template', source: project })}><Thumbnail project={project} /></button><div className="library-card-body"><h3>{project.name}</h3><p>{project.description}</p><button className="btn btn-outline btn-sm" disabled={busy} onClick={() => onCreate({ mode: 'template', source: project })}>Use template <ArrowUpRight size={14} /></button></div></article>)}</div>
    <p className="library-storage-note">{storageMode === 'opfs' ? 'Stored in this browser — export a backup ZIP regularly. Clearing site data removes these projects.' : 'Each project is a folder on your computer. Studio remembers the folders you open here.'}</p>
  </section>;
}

export function CreateProjectDialog({ initial = {}, templates, busy, aiEnabled = false, aiSettings, onCreate, onClose }) {
  const [kind, setKind] = useState(initial.kind || 'landing'), [mode, setMode] = useState(initial.mode === 'ai' && !aiEnabled ? 'template' : initial.mode || (aiEnabled ? 'ai' : 'template'));
  const [attachments, setAttachments] = useState([]), [useOnPage, setUseOnPage] = useState(false), [imageChoice, setImageChoice] = useState(initial.generateImages), [settings, setSettings] = useState(null);
  const [name, setName] = useState(initial.source ? `${initial.source.name} landing` : ''), [prompt, setPrompt] = useState('');
  const [sourceId, setSourceId] = useState(initial.source?.id || studioStarters[0].id), [error, setError] = useState('');
  const dialog = useRef(null), formId = useId(), choices = [...templates, ...studioStarters];
  useEffect(() => { dialog.current.showModal(); }, []);
  useEffect(() => { if (!aiEnabled) setMode(value => value === 'ai' ? 'template' : value); }, [aiEnabled]);
  useEffect(() => {
    let alive = true;
    const load = () => {
      if (!aiEnabled || !aiSettings) { setSettings({}); return; }
      aiSettings.load().then(value => { if (alive) setSettings({ imageModel: value.imageModel }); }).catch(cause => { if (alive) { setSettings({}); setError(cause.message); } });
    };
    load(); window.addEventListener('trafficops-ai-settings', load);
    return () => { alive = false; window.removeEventListener('trafficops-ai-settings', load); };
  }, [aiEnabled, aiSettings]);
  // Template/blank submit through the hidden form (the composer is a form of its own, forms cannot nest);
  // the AI brief submits through BriefComposer with its File[] attachments.
  async function create(brief) {
    if (busy || (mode === 'ai' && settings === null)) return false; setError('');
    if (brief && !brief.text.trim()) { setError(BRIEF_REQUIRED); return false; }
    // Resolve the default at generation time: the user may connect an image
    // model in the editor after creating this project's initial brief.
    try { await onCreate({ kind, mode, name: name.trim(), prompt: (brief?.text ?? prompt).trim(), attachments: brief ? await briefAttachments(brief.attachments, brief.useOnPage) : [], generateImages: imageChoice, source: choices.find(item => item.id === sourceId) }); }
    catch (cause) { setError(cause.message); return false; }
  }
  return <dialog ref={dialog} className="modal" aria-labelledby="create-project-title" onCancel={event => { if (busy) event.preventDefault(); else onClose(); }}><div className="modal-box create-project-modal"><form id={formId} hidden onSubmit={event => { event.preventDefault(); create(); }} /><div className="dialog-heading"><div><span className="section-kicker">START SOMETHING</span><h2 id="create-project-title">New project</h2></div><button type="button" className="btn btn-ghost btn-sm btn-square" aria-label="Close new project" disabled={busy} onClick={onClose}><X size={18} /></button></div><fieldset disabled={busy}>
    <div className={`creation-mode ${aiEnabled ? '' : 'manual-only'}`} role="group" aria-label="Creation method">{[['template', 'From template', LayoutTemplate], ['blank', 'From scratch', FileCode2], ...(aiEnabled ? [['ai', 'With AI', Sparkles]] : [])].map(([value, label, Icon]) => <button type="button" key={value} aria-pressed={mode === value} onClick={() => { setMode(value); setError(''); }}><Icon size={16} />{label}</button>)}</div>
    {mode !== 'ai' && <label className="field"><span>Project name</span><input form={formId} className="input w-full" autoFocus required maxLength={120} value={name} placeholder="My next idea" onChange={event => setName(event.target.value)} /></label>}
    {mode === 'template' && <label className="field"><span>Starting template</span><select form={formId} className="select w-full" value={sourceId} onChange={event => setSourceId(event.target.value)}>{choices.map(item => <option key={item.id} value={item.id}>{item.name}{item.builtin ? ' · Starter' : ' · Your template'}</option>)}</select><small>Creates an independent copy, including content and assets.</small></label>}
    {mode === 'blank' && <p className="create-explanation">Start with a minimal editable page. Add files and make it yours.</p>}
    {mode === 'ai' && <><BriefComposer value={prompt} onChange={setPrompt} attachments={attachments} onAttachmentsChange={setAttachments} settings={settings} imageChoice={imageChoice} onImageChoiceChange={setImageChoice} useOnPage={useOnPage} onUseOnPageChange={setUseOnPage} disabled={busy || settings === null} onSubmit={create} placeholder="Describe your landing page" autoFocus /><p className="field-help">A new project and its first conversation open after you send the brief. You can connect your AI key in the editor.</p></>}
    <details className="create-project-options" open={mode !== 'ai'}><summary>{mode === 'ai' ? 'Project options' : 'Project type'}</summary>{mode === 'ai' && <label className="field"><span>Project name (optional)</span><input className="input w-full" maxLength={120} value={name} placeholder="Named from your brief" onChange={event => setName(event.target.value)} /></label>}<div className="create-kind" role="group" aria-label="Project type">{[['landing', 'Landing page', 'A page ready to customize and export.'], ['template', 'Reusable template', 'A starting point for future landing pages.']].map(([value, title, text]) => <button type="button" key={value} aria-pressed={kind === value} onClick={() => setKind(value)}><strong>{title}</strong><span>{text}</span></button>)}</div></details>
    </fieldset>{error && <p className="inline-error" role="alert">{error}</p>}<div className="modal-action"><button type="button" className="btn btn-ghost" disabled={busy} onClick={onClose}>Cancel</button>{mode !== 'ai' && <button form={formId} className="btn btn-primary" disabled={busy}>{busy ? 'Creating…' : `Create ${kind === 'template' ? 'template' : 'landing'}`}</button>}</div></div></dialog>;
}
